---
- name: ec2-52-198-195-60.ap-northeast-1.compute.amazonaws.com
  hosts: all
  become: yes
  user: ec2-user
  vars:
    main_username: fusic
    main_password: fusic
    stage: production
    docroot: /var/www/html/htdocs/current/public
    domain: ec2-52-198-195-60.ap-northeast-1.compute.amazonaws.com
  roles:
    - common
    - nginx
    - php74
